apiVersion: v1
kind: Pod
metadata: 
  name: emptydir-example
spec: 
  containers:
  - name: app
    image: busybox
    command: ["sleep","3600"]
    volumeMounts:
    - mountPath: /cache
      name: temp-storage
  volumes:
  - name: temp-storage
    emptyDir: {}     