apiVersion: v1
kind: Pod
metadata:
   name: hostpath-example
spec:
  containers:
  - name: app
    image: busybox
    command: ["sleep","3600"]
    volumeMounts:
    - mountPath: /data
      name: host-volume
  volumes:
  - name: host-volume
    hostpath:
      path: /var/data
      type: Directory     

      
        