apiVersion: batch/v1
kind: CronJob
metadata:
   name: hello-cron
spec:
   schedule: "*/5 * * * *"
   jobTemplate:
     spec:
       template:
         spec:
            containers:
            - name: hello
              image: busybox
              args:
              - /bin/sh
              - date; echo "Hello from the kubernetes"
            restartPolicy: OnFailure     