apiVersion: v1
kind: Pod
metadata:
 name: node-affinity-pod
spec:
 affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Zone"
          operator: In
          values:
          - us-west-1
          - us-west-2
 containers:
 - name: my-container
   image: nginx         

