apiVersion: v1
kind: Pod
metadata:
  name: pod-using-pvc
spec:
  containers:
  - name: app
    image: busybox
    command: ["sleep","3600"]
    volumeMounts:
    - mountPath:
      name: storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc-example      