apiVersion: v1
kind: Pod
metadat:
 name: sai
spec:
 containers:
 - name: sai
   image: ubuntu:latest
   command: ["sleep", "2000"]
   resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1"   