apiVersion: v1
kind: Pod
metadata:
   name: mypod
spec:
   affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/e2e-az-zone
            operator: In
            values:
            - zoneA
   containers:
   - name: nginx
     image: nginx
              

