apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
  containers:
  - name: gpu-container
    image: ubuntu/latest  
